---
# yamllint disable line-length
name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        uses: docker://ghcr.io/codfish/semantic-release-action
        id: semantic
        with:
          branches: |
            [
              'main'
            ]
          additional-packages: |
            [
              'conventional-changelog-conventionalcommits'
            ]
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
